### PR TITLE
Merging the hoverboard master + making small-ish changes along the way

### PR DESCRIPTION
**Pull request by emedvedev**
Shouldn't have pushed so many different changes into a single PR, but I guess nobody cares anyway.

1. Merged the Hoverboard master (this implies migration to Firestore, so we're going to have a bit of a downtime when I start merging this). Mostly did this because a couple things in our template version are broken, like CSS on subpages.

2. Changed all logos and social media images.

3. Fixed the subpages (CoC, reporting guidelines, incident handling guidelines).

4. Moved privacy and imprint into the footer.

5. A bunch of copy and config fixes (like correct twitter links and hashtags, etc.).

### CODE REVIEW

**Comment by emedvedev** [comment]
So I think what I'll do is spin up a dev Firebase project that will run from this branch, and then, instead of testing the entire 91-file PR, we'll just test the actual website.

**Comment by emedvedev** [comment]
@jossiwolf fixed.

So aside from the Firestore migration, the main page still needs better content and some structural changes, which I'll handle, but subpages also need some love, and if someone could take that on, I'd really appreciate it:

1. `/conduct`: fix the formatting where necessary.
2. `/violation-reporting`: formatting.
3. `/incident-handling`: formatting.
4. `/imprint`: I just blindly cut the HTML piece into the Markdown doc, and it looks just as ugly as you would expect. Also the imprint itself has to be changed; Madlaina has all the info.
5. `/privacy`: also needs to be converted to Markdown.
6. `/team`: didn't we use to have people there? Must've screwed that up by the merge.
7. `/faq`: I can see somebody was working on it, and most of the content is adapted, but some links are broken and irrelevant, some content doesn't apply to us, and some is missing. @jossiwolf I'd recommend you to take a look.

@jossiwolf @thebino maybe you could split the pages between the two of you and make the first pass, and then I'll put some finishing touches along with rearranging the main page?

**Comment by emedvedev** [comment]
Alright, I'm done.

1. Rewrote most of the main page copy.
2. Renovated the main page: replaced broken links (e.g. to the blog), removed all the broken references to ticket sales, replaced the mailing list link with a twitter link (let me know if we want the mailing list back), added news into "the latest news," added all current partners, fixed the "become a partner" link.
3. Wrote the FAQ (the previous version was a bit clumsy and mostly cloned from DevFest Ukraine).
4. Added the accessibility statement page (link in the footer). Thanks to @jossiwolf for the statement itself.
5. Added the reporting guidelines and incident handling pages.
6. Reformatted all subpages (code of conduct + guidelines, imprint, privacy policy), thanks to @thebino for his help.
7. Merged the latest Hoverboard master, deployed the DB into Firestore.

There were more changes, but too many to remember. Long story short, nothing is broken, and everything looks neat and up-to-date (unless I missed something, which I most certainly did, but what can you do).

@thebino @jossiwolf let's test this and roll out—this is one of the last things we need to do before we can kick off the ticket sales. :)

**Comment by jossiwolf** [comment]
@emedvedev Neat, everything works!

Awesome FAQ Section! Love the new colours too.

I changed some information in the accessibility statement which I think was left over from copy and pasting :P 

I think that new colour of the "Ticket Sales are starting soon" button is a bit invisible against the dark background, should we change it to a better visible colour?

Otherwise, I'm *super* happy about the PR!

**Comment by emedvedev** [comment]
@jossiwolf done :)

**Comment by emedvedev** [comment]
Woohoo, it's happening!

**Pull request merged**
