### PR TITLE
add pictures for Google Assistant: Action on Google "DACHFest Conference"

### PR DESCRIPTION
**Pull request by Anialeinchen**

### CODE REVIEW

**Comment by emedvedev** [comment]
1. Can we move it to `googleassistant` instead of `action_on_google`? Sorry for being picky, but hopefully won't make a difference :)
2. `main.PNG` is not from the current website.
3. `when.png` would ideally show that it's two days, not just one.

**Comment by emedvedev** [comment]
There's also both `tickets` and `dachfest_tickets` that are almost identical

**Comment by Anialeinchen** [comment]
> 1. Can we move it to `googleassistant` instead of `action_on_google`? 
[Done] I used google-assistant to be consistent.
> 2. `main.PNG` is not from the current website. 
I think it looks less cluttered on a small screen, I thought I would make use of the broken worker thread ;) but I can change it if you prefer.
> 3. `when.png` would ideally show that it's two days, not just one.  [Done]
> 4. There's also both tickets and dachfest_tickets that are almost identical. [Done]
I added some new pictures. I used other graphics than the ones from your Medium articles. 
Graphics look better on the Google Assistant's Basic Cards when they are more vertical than horizontal.

**Comment by emedvedev** [comment]
> I think it looks less cluttered on a small screen, I thought I would make use of the broken worker thread ;) but I can change it if you prefer.
Please do, it may look less cluttered, but unfortunately the grey logo is just incorrect :( And "Be a hero. Inspire others" is a leftover from Ukraine.

**Comment by Anialeinchen** [comment]
> may look less cluttered, but unfortunately the grey logo is just incorrect :( And "Be a hero. Inspire others" is a leftover from Ukraine. [Done]

**Comment by miquelbeltran** [comment]
please be aware that https://github.com/DACHFest/dachfest.com/blob/2575abf2685164b819f109c15c559a0e5626c7c0/images/google-assistant/sketchnoting_workshop.jpeg is 7+ megabytes, may be worth resizing it for better user experience

**Comment by helmuthb** [comment]
I would also suggest using consistent file extensions, e.g. always ".png" and not ".PNG", and ".jpg" instead of ".jpeg"

**Comment by Anialeinchen** [comment]
> I would also suggest using consistent file extensions, e.g. always ".png" and not ".PNG", and ".jpg" instead of ".jpeg" [Done]

Thanks!

**Pull request merged**
