### PR TITLE
removed blog images from the hoverboard template & minor bugfix for md-pages

### PR DESCRIPTION
**Pull request by mpoehler**
The images in the blog folder are not used, they are from the example hoverboard blog posts. They will be precached by the service-worker and that is uneccessary!

There was a small bug in the markdown pages which causes a javascirpt error in the console.

### CODE REVIEW

**Comment by emedvedev** [comment]
`<div class="content-wrapper">` adds a lot of weird padding on the top of the pages (I'm not even sure what's supposed to be there), so if we need it back for JS to work correctly, should we maybe hide it with `display:none`?

The images are a good catch, thanks a lot! Saves a lot of data / space.

**Comment by mpoehler** [comment]
The content-wrapper adds a directory, can be seen in privacy and imprint...
bildschirmfoto 2018-09-08 um 23 53 07

If not ok, I can revert that and fix it in the code to remove the error.

**Comment by emedvedev** [comment]
I think it's better to remove: we don't need it in most pages, and even in the privacy policy looks a bit weird :) If you don't have time, I can fix it tomorrow, not a problem at all.

**Comment by mpoehler** [comment]
GIve me a minute ;-)

**Comment by mpoehler** [comment]
That should work.

**Comment by emedvedev** [comment]
Awesome!

**Pull request merged**
